workflows:
  react-native-expo:
    name: React Native Expo Build
    max_build_duration: 60
    environment:
      node: latest
      npm: latest
      java: 17
      android: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: |
          npx expo prebuild
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
