workflows:
  build-android:
    name: Build Android APK
    environment:
      node: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: |
          npx expo prebuild
          npx expo run:android --variant release
    artifacts:
      - android/app/build/outputs/**/*.apk
